// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   env: string,

   runtime: string,

   isDev: boolean,

   isProd: boolean,

   baseURL: string,

   db: {
      connectionString: string,
   },

   openai: {
      apiKey: string,
   },

   auth: {
      secret: string,

      social: {
         google: {
            clientId: string,

            clientSecret: string,
         },

         kakao: {
            clientId: string,

            clientSecret: string,
         },
      },
   },
  }
}
export {}