// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**:all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/api/auth/[...all]').default>>>>
    }
    '/api/health': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/api/health').default>>>>
    }
  }
}
export {}