name = "nuxt-fullstack-starter"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2025-01-20"
rules = [{ type = "ESModule", globs = ["**/*.js"] }]
compatibility_flags = ["nodejs_compat"]
[site]
bucket = ".output/public"
