name: Cleanup Preview Deployment

on:
  delete:
  workflow_dispatch:

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    if: |
      github.event.ref_type == 'branch' && 
      startsWith(github.event.ref, 'preview/')
    
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.7.0
        run_install: false
    
    - name: Install Infisical CLI
      run: |
        npm install -g @infisical/cli

    - name: Install dependencies
      run: pnpm install
      env:
        CI: true
    
    - name: Extract branch name
      shell: bash
      run: |
        branch_name=${GITHUB_EVENT_REF#preview/}
        echo "PREVIEW_NAME=$branch_name" >> $GITHUB_ENV
        echo "WORKER_NAME=nuxt-fullstack-starter-preview-$branch_name" >> $GITHUB_ENV
        echo "Cleaning up preview for branch: $branch_name"
    
    - name: Delete Preview Worker
      run: |
        cd app
        
        # Get environment variables
        pnpm run prod.env
        
        # Delete the worker
        npx dotenv-cli -e .env.prod -- wrangler delete --name $WORKER_NAME --force || echo "Worker $WORKER_NAME not found or already deleted"
      env:
        INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
    
    - name: Report Cleanup
      if: always()
      run: |
        curl -X POST https://api.bino.blog/enterprise/notifications/github-actions \
          -H "Content-Type: application/json" \
          -d '{
            "github": ${{ toJSON(github) }},
            "status": "${{ job.status }}",
            "action": "cleanup",
            "preview": {
              "branch": "${{ env.PREVIEW_NAME }}",
              "worker": "${{ env.WORKER_NAME }}"
            }
          }'